### ISSUE TITLE
can't run successfully

### ISSUE THREAD

**Issue by Doctor-JZL** [RUCAIBox/CORE#4]
Hi, I really appreciate your work "CORE".  After reading the paper, I couldn't wait to download and run your open source code. However, there is an error here "ValueError: train_neg_sample_args [{'distribution': 'uniform', 'sample_num': 1, 'alpha': 1.0, 'dynamic': False, 'candidate_num': 0}] should be None when the loss_type is CE.". I can't find the reason. So I'd really appreciate it if you could help me.

**Comment by hyp1231** [comment]
Hi, thanks for your attention! I guess a quick way to solve this is `pip install recbole==1.0.1`.

The reason is that just several days ago, RecBole has released its newest version 1.1.1, and CORE has not yet been updated. Thanks for pointing out this, I'll fix the requirements in README, and maybe update CORE's code to fit the new version later.

**Comment by Doctor-JZL** [comment]
OK，it runs sucessfully on recbole==1.0.1. Thanks for your help. I will continue to follow your work.
